### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by kmarsh** [servesimple/servesimple#2]
Since not every organization has the same data requirements, the `Person` model should support custom fields, definable on a per-`Account` and per-`Role` basis.

Initial field types should include:
- Text
- Choice (including multiple)
- Number
- Date
- Boolean

Redmine offers [similar functionality](http://www.redmine.org/projects/redmine/wiki/RedmineCustomFields), perhaps some code could be used or at least learned from
## Todo
- [ ] `CustomField` model
  - `account_id`, `name`, `title`, `type`, `description`, `choices` (Multiple choice only)
- [ ] `custom_fields_roles` table
- [ ] Admin interface to define types
- [ ] Update forms to display fields with proper input types
- [ ] Migration to add to model: (use `hstore` type)
- [ ] `as_indexed_json` could be adapted to include them
- [ ] Update index to display in table
